{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "gaussian_cache = {}\n",
    "\n",
    "def get_gaussian_weight(patch_size, device):\n",
    "    key = (patch_size, device)\n",
    "    if key in gaussian_cache:\n",
    "        return gaussian_cache[key]\n",
    "\n",
    "    dz, dy, dx = patch_size\n",
    "    z = torch.linspace(-1, 1, dz, device=device)\n",
    "    y = torch.linspace(-1, 1, dy, device=device)\n",
    "    x = torch.linspace(-1, 1, dx, device=device)\n",
    "\n",
    "    zz, yy, xx = torch.meshgrid(z, y, x, indexing='ij')\n",
    "    g = torch.exp(-(xx**2 + yy**2 + zz**2) / 0.5)\n",
    "    g = g / g.max()\n",
    "    g = g.half().unsqueeze(0).unsqueeze(0)  # [1,1,D,H,W]\n",
    "\n",
    "    gaussian_cache[key] = g\n",
    "    return g"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "@torch.no_grad()\n",
    "def sliding_window_fast(model, image, patch_size, stride, sw_batch_size=4):\n",
    "    \"\"\"\n",
    "    Ускоренная sliding-window inference.\n",
    "    Без вложенных циклов.\n",
    "    \"\"\"\n",
    "\n",
    "    B, C, D, H, W = image.shape\n",
    "    pd, ph, pw = patch_size\n",
    "    sd, sh, sw = stride\n",
    "    device = image.device\n",
    "\n",
    "    # координаты начала окон\n",
    "    ds = list(range(0, D - pd + 1, sd))\n",
    "    hs = list(range(0, H - ph + 1, sh))\n",
    "    ws = list(range(0, W - pw + 1, sw))\n",
    "\n",
    "    if ds[-1] != D - pd: ds.append(D - pd)\n",
    "    if hs[-1] != H - ph: hs.append(H - ph)\n",
    "    if ws[-1] != W - pw: ws.append(W - pw)\n",
    "\n",
    "    coords = [(d, h, w) for d in ds for h in hs for w in ws]\n",
    "\n",
    "    num_classes = model.out_channels\n",
    "\n",
    "    output = torch.zeros((B, num_classes, D, H, W),\n",
    "                         device=device, dtype=torch.float32)\n",
    "    norm_map = torch.zeros((1, 1, D, H, W),\n",
    "                           device=device, dtype=torch.float32)\n",
    "\n",
    "    weight = get_gaussian_weight(patch_size, device).float()\n",
    "\n",
    "    # === батчевый прогон ===\n",
    "    for i in range(0, len(coords), sw_batch_size):\n",
    "\n",
    "        batch_coords = coords[i:i+sw_batch_size]\n",
    "\n",
    "        patches = torch.cat([\n",
    "            image[..., d:d+pd, h:h+ph, w:w+pw]\n",
    "            for (d, h, w) in batch_coords\n",
    "        ], dim=0)\n",
    "\n",
    "        with torch.amp.autocast(\"cuda\"):\n",
    "            preds = model(patches)\n",
    "\n",
    "        preds = preds.float()\n",
    "\n",
    "        for j, (d, h, w) in enumerate(batch_coords):\n",
    "            output[..., d:d+pd, h:h+ph, w:w+pw] += preds[j:j+1] * weight\n",
    "            norm_map[..., d:d+pd, h:h+ph, w:w+pw] += weight\n",
    "\n",
    "    return output / norm_map.clamp_min(1e-6)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "def train_one_epoch(model, loader, optimizer, criterion, scaler):\n",
    "    model.train()\n",
    "    total_loss = 0\n",
    "    dice_scores = {'WT':0, 'TC':0, 'ET':0}\n",
    "\n",
    "    for images, masks in loader:\n",
    "        images = images.contiguous().to(device)\n",
    "        masks = masks.to(device)\n",
    "\n",
    "        optimizer.zero_grad(set_to_none=True)\n",
    "\n",
    "        with torch.amp.autocast(\"cuda\"):\n",
    "            outputs = model(images)\n",
    "            loss = criterion(outputs, masks)\n",
    "        \n",
    "        scaler.scale(loss).backward()\n",
    "        scaler.unscale_(optimizer)\n",
    "        torch.nn.utils.clip_grad_norm_(model.parameters(), 12)\n",
    "        \n",
    "        scaler.step(optimizer)\n",
    "        scaler.update()\n",
    "\n",
    "        total_loss += loss.item()\n",
    "\n",
    "        # DICE scores\n",
    "        scores = dice_score_wt_tc_et(outputs, masks)\n",
    "        for k in dice_scores:\n",
    "            dice_scores[k] += scores[k]\n",
    "\n",
    "    mean_loss = total_loss / len(loader)\n",
    "    mean_dice = {k: dice_scores[k]/len(loader) for k in dice_scores}\n",
    "\n",
    "    return mean_loss, mean_dice"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "@torch.no_grad()\n",
    "def validate_one_epoch(model, loader, criterion, patch_size=(128,128,128),\n",
    "                       stride=(96,96,96)):\n",
    "\n",
    "    model.eval()\n",
    "    total_loss = 0\n",
    "    dice_scores = {'WT':0, 'TC':0, 'ET':0}\n",
    "\n",
    "    for images, masks in loader:\n",
    "        images = images.to(device, non_blocking=True)\n",
    "        masks  = masks.to(device, non_blocking=True)\n",
    "\n",
    "        logits = sliding_window_fast(model, images, patch_size, stride, sw_batch_size=4)\n",
    "\n",
    "        loss = criterion(logits, masks)\n",
    "\n",
    "        total_loss += loss.item()\n",
    "\n",
    "        scores = dice_score_wt_tc_et(logits, masks)\n",
    "\n",
    "        for k in dice_scores:\n",
    "            dice_scores[k] += scores[k]\n",
    "\n",
    "    mean_loss = total_loss / len(loader)\n",
    "    mean_dice = {k: dice_scores[k]/len(loader) for k in dice_scores}\n",
    "    return mean_loss, mean_dice"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "epochs = 40\n",
    "\n",
    "model = FastResidualUNet3D(in_channels=4, num_classes=4, base_c=32).to(device)\n",
    "scaler = torch.amp.GradScaler(\"cuda\")\n",
    "criterion = TCFocusedLoss(max_epochs=epochs).to(device)\n",
    "optimizer = torch.optim.AdamW(model.parameters(), lr=1e-4, weight_decay=1e-4, fused=True)\n",
    "scheduler = torch.optim.lr_scheduler.CosineAnnealingWarmRestarts(\n",
    "    optimizer, T_0=10, T_mult=2, eta_min=5e-6)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "stride = (96,96,96)\n",
    "best_val = 0.0\n",
    "epochs_no_improve = 0\n",
    "patience = 10\n",
    "\n",
    "for epoch in range(epochs):\n",
    "\n",
    "    criterion.set_epoch(epoch)\n",
    "\n",
    "    train_loss, train_dice = train_one_epoch(\n",
    "        model, train_loader, optimizer, criterion,\n",
    "        scaler\n",
    "    )\n",
    "\n",
    "    torch.cuda.empty_cache()\n",
    "\n",
    "    # --- validation ---\n",
    "    val_loss, val_dice = validate_one_epoch(\n",
    "        model,\n",
    "        val_loader,\n",
    "        criterion,\n",
    "        stride=stride\n",
    "    )\n",
    "\n",
    "    mean_val_dice = (val_dice['WT'] +\n",
    "        val_dice['TC'] +\n",
    "        1.5 * val_dice['ET']\n",
    "    ) / 3.5\n",
    "      \n",
    "\n",
    "    scheduler.step()\n",
    "\n",
    "    print(f\"Epoch [{epoch+1}/{epochs}]\")\n",
    "    print(f\"  Train Loss: {train_loss:.4f}\")\n",
    "    print(f\"  Val   Loss: {val_loss:.4f}\")\n",
    "\n",
    "    print(f\"  Train Dice: WT={train_dice['WT']:.4f},TC={train_dice['TC']:.4f},ET={train_dice['ET']:.4f}\")\n",
    "    print(f\"  Val   Dice: WT={val_dice['WT']:.4f},TC={val_dice['TC']:.4f},ET={val_dice['ET']:.4f}\")\n",
    "    print(f\"  Mean val Dice: {mean_val_dice:.4f}\")\n",
    "\n",
    "    # --- Early stopping и сохранение ---\n",
    "    if mean_val_dice > best_val:\n",
    "        best_val = mean_val_dice\n",
    "        epochs_no_improve = 0\n",
    "        torch.save(model.state_dict(), \"best_model.pth\")\n",
    "        print(\"✅ Saved new best model\")\n",
    "\n",
    "    else:\n",
    "        epochs_no_improve += 1\n",
    "        if epochs_no_improve >= patience:\n",
    "            print(\"Early stopping triggered\")\n",
    "            break\n",
    "    print(\"-\"*50)"
   ]
  }
 ],
 "metadata": {
  "kaggle": {
   "accelerator": "none",
   "dataSources": [
    {
     "datasetId": 9221004,
     "sourceId": 14476048,
     "sourceType": "datasetVersion"
    },
    {
     "isSourceIdPinned": false,
     "modelId": 589527,
     "modelInstanceId": 577204,
     "sourceId": 764080,
     "sourceType": "modelInstanceVersion"
    }
   ],
   "dockerImageVersionId": 31236,
   "isGpuEnabled": false,
   "isInternetEnabled": true,
   "language": "python",
   "sourceType": "notebook"
  },
  "kernelspec": {
   "display_name": "Python [conda env:practicum]",
   "language": "python",
   "name": "conda-env-practicum-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.21"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
